# ------------------------------------------------------------
# The following values are for the link on the AIE UI.
# ------------------------------------------------------------
ezua:
  virtualService:
    endpoint: "ai-q.${DOMAIN_NAME}"
    istioGateway: "istio-system/ezaf-gateway"

# ------------------------------------------------------------
# The following values are for the AIQ AIRA backend service.
# ------------------------------------------------------------

replicaCount: 1

# The name of the image pull secret to use for the AIQ container images.
# Either create the secret manually and update the name here
# or update the imagePullSecret.password with your NGC API key
ngcImagePullSecretName: "ngc-secret"

imagePullSecret:
  create: false
  name: "ngc-secret"
  registry: "nvcr.io"
  username: "$oauthtoken"
  password: "" #UPDATE THIS

# The image repository and tag for the AIQ AIRA backend service.
image:  
  repository: nvcr.io/nvidia/blueprint/aira-backend
  tag: v1.1.0
  pullPolicy: IfNotPresent

# The service type and port for the main AIQ AIRA backend service
service:
  port: 3838

# Update each value according to your desired configuration.
config:
  # The instruct_ settings are for the general purpose Q&A LLM
  instruct_model_name: "meta/llama-3.3-70b-instruct"
  instruct_temperature: "0.0"
  instruct_api_key: "not-needed" 
  instruct_base_url: "http://nim-llm.aira.svc.cluster.local:8000/v1"
  # The nemotron_ settings are for the reasoning LLM
  nemotron_api_key: "not-needed" # not needed as we use the nemotron service from the RAG deployment which does not require an API key
  nemotron_model_name: "nvidia/llama-3.3-nemotron-super-49b-v1"
  nemotron_temperature: "0.5"
  nemotron_base_url: "http://nim-llm.nv-nvidia-blueprint-rag.svc.cluster.local:8000/v1" # provided by the RAG deployment 
  nemotron_max_tokens: "5000"
  nemotron_stream: "true"
  # Enter your Tavily API key here to enable web search
  tavily_api_key: "" #UPDATE THIS
  # Enter the IP address of the RAG services
  rag_ingest_url: "http://ingestor-server.nv-nvidia-blueprint-rag.svc.cluster.local:8082" # provided by the RAG deployment 
  rag_url: "http://rag-server.nv-nvidia-blueprint-rag.svc.cluster.local:8081" # provided by the RAG deployment 
  rag_api_key: "" #Typically not required
  milvus_host: "milvus.nv-nvidia-blueprint-rag.svc.cluster.local" # provided by the RAG deployment 
  milvus_port: "19530"

# Do not update this command. It is the default command to launch the AI-Q backend service.
command: "/entrypoint.sh"


# ------------------------------------------------------------
# The following values are for the instruct LLM service
# The nemotron llm is assumed to be deployed via the RAG helm chart
# ------------------------------------------------------------

ngcApiSecret:
  name: "ngc-api"
  password: "" # UPDATE THIS
  create: false

nim-llm:
  enabled: false
  service:
    name: "nim-llm"
  image:
      repository: nvcr.io/nim/meta/llama-3.3-70b-instruct
      pullPolicy: IfNotPresent
      tag: "1.8.5"
  resources:
    limits:
      nvidia.com/gpu: 2
    requests:
      nvidia.com/gpu: 2
  model:
    name: "meta/llama-3.3-70b-instruct"

# ------------------------------------------------------------
# The following values are for the AIQ AIRA frontend service.
# ------------------------------------------------------------

# The frontend application is a React web app. We recommend a NodePort so the frontend will be accessible at <your-node-ip>:3001
frontend:
  enabled: true
  # Update the value below to the IP address and port of the nginx service
  proxyUrl: http://aira-nginx.aira.svc.cluster.local:8051
  service:
    port: 3001
    targetPort: 3001

  image:
    repository: nvcr.io/nvidia/blueprint/aira-frontend
    tag: v1.1.0
    pullPolicy: IfNotPresent

  replicaCount: 1

# ------------------------------------------------------------
# The following values are optional utility services
# ------------------------------------------------------------

# Enables the Phoenix tracing service
phoenix:
  enabled: true
  image:
    repository: arizephoenix/phoenix
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi