apiVersion: v2
appVersion: 1.0.0
dependencies:
- name: nim-library
  repository: file://charts/library_chart/
  version: '>0.0.1'
description: Application chart for NIM to be deployed using helm
keywords:
- NIM
- application
kubeVersion: '>=v1.23.0-0'
name: nvidia-nim-paddleocr
type: application
version: 1.2.0
