apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-server
  labels:
    app: rag-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rag-server
  template:
    metadata:
      labels:
        app: rag-server
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      containers:
        - name: rag-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - -c
          - apt install wget -y && wget https://raw.githubusercontent.com/ai-solution-eng/blueprints/refs/heads/main/enterprise-rag/2.1.0-hybrid/utils.py
            -O /workspace/src/utils.py && uvicorn src.server:app --port 8081 --host
            0.0.0.0 --workers {{ .Values.server.workers }}
          command:
          - /bin/sh
          ports:
            - containerPort: 8081
          {{ if .Values.envVars }}
          env:
            {{ if .Values.ngcApiSecret }}
            - name: NVIDIA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ngcApiSecret.name }}
                  key: NGC_API_KEY
            {{- end }}
            {{- if .Values.envVars }}
            {{- range $k, $v := .Values.envVars }}
            - name: "{{ $k }}"
              value: "{{ $v }}"
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: prompt-volume
              mountPath: /prompt.yaml
              subPath: prompt.yaml
      volumes:
        - name: prompt-volume
          configMap:
            name: prompt-config
            defaultMode: 0555