apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.ezua.virtualService.endpoint | quote }}
  gateways:
  - {{ .Values.ezua.virtualService.istioGateway }}
  hosts:
    - ai-q.ai-application.staging.discover.hpepcai.com
  http:
    - match:
        - uri:
            regex: .*\/v1\/(status|documents|collections)(\/|$)(.*)
      rewrite:
        uriRegexRewrite:
          match: .*\/v1\/(status|documents|collections)(\/|$)(.*)
          rewrite: /v1/\1
      route:
        - destination:
            host: ingestor-server.{{ .Values.config.rag_blueprint_namespace }}.svc.cluster.local
            port:
              number: 8082
    - match:
        - uri:
            regex: >-
              .*\/v2\/protected\/aiq\/v1\/(status|documents|collections)(\/|$)(.*)
      rewrite:
        uriRegexRewrite:
          match: .*\/v2\/protected\/aiq\/v1\/(status|documents|collections)(\/|$)(.*)
          rewrite: /v1/\1
      route:
        - destination:
            host: ingestor-server.{{ .Values.config.rag_blueprint_namespace }}.svc.cluster.local
            port:
              number: 8082
    - match:
        - uri:
            regex: .*\/v2\/protected\/aiq\/v1\/files
      rewrite:
        uri: /v1/documents
      route:
        - destination:
            host: ingestor-server.{{ .Values.config.rag_blueprint_namespace }}.svc.cluster.local
            port:
              number: 8082
    - match:
        - uri:
            regex: >-
              .*\/v2\/protected\/aiq\/v1\/(generate_query|generate_summary|artifact_qa)(.*)
      rewrite:
        uriRegexRewrite:
          match: >-
            .*\/v2\/protected\/aiq\/v1\/(generate_query|generate_summary|artifact_qa)(.*)
          rewrite: /\1\2
      route:
        - destination:
            host: {{ .Release.Name }}-aira-backend.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 3838
    - match:
        - uri:
            regex: .*\/v2\/protected\/aiq\/default_collections(.*)
      rewrite:
        uriRegexRewrite:
          match: .*\/v2\/protected\/aiq\/default_collections(.*)
          rewrite: /default_collections/\1
      route:
        - destination:
            host: {{ .Release.Name }}-aira-backend.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 3838
    - directResponse:
        body:
          string: OK
        status: 200
      match:
        - uri:
            regex: .*\/v2\/protected\/aiq\/health
    - directResponse:
        body:
          string: OK
        status: 200
      match:
        - uri:
            regex: .*\/v2\/protected\/aiq\/keepalive
    - directResponse:
        body:
          string: OK
        status: 200
      match:
        - uri:
            regex: .*\/keepalive
    - directResponse:
        body:
          string: OK
        status: 200
      match:
        - uri:
            regex: .*\/health
    - match:
        - uri:
            regex: .*\/v2\/protected\/aiq\/(.*)
      rewrite:
        uriRegexRewrite:
          match: .*\/v2\/protected\/aiq\/(.*)
          rewrite: /v2/protected/aiq/\1
      route:
        - destination:
            host: {{ .Release.Name }}-aira-frontend.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 3001
    - match:
        - uri:
            regex: .*\/v2\/(.*)
      rewrite:
        uriRegexRewrite:
          match: .*\/v2\/\/(.*)
          rewrite: /v2/\1
      route:
        - destination:
            host: {{ .Release.Name }}-aira-frontend.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.frontend.service.targetPort }}
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Release.Name }}-aira-frontend.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.frontend.service.targetPort }}
  tls:
    - match:
        - port: 443
          sniHosts:
            - {{ .Values.ezua.virtualService.endpoint }}
      route:
        - destination:
            host: {{ .Release.Name }}-aira-frontend.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.frontend.service.targetPort }}
