---
{{- if .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "nim-vlm.labels" . | nindent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.metrics.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nim-vlm.selectorLabels" . | nindent 6 }}
      {{- if .Values.multiNode.enabled }}
      {{- if (or (.Capabilities.APIVersions.Has "leaderworkerset.x-k8s.io/v1") .Values.multiNode.leaderWorkerSet.enabled) }}
      nim-vlm-role: "leader"
      {{- else }}
      training.kubeflow.org/replica-index: "0"
      {{- end }}
      {{- end }}
  endpoints:
  - port: {{ $.Values.model.legacyCompat | ternary "metrics" "http-openai" }}
{{- end -}}
