apiVersion: v2
dependencies:
- alias: nemoretriever-page-elements-v2
  condition: nemoretriever-page-elements-v2.deployed
  name: nvidia-nim-nemoretriever-page-elements-v2
  repository: alias:nvidia-nim
  version: 1.2.0
- alias: nemoretriever-graphic-elements-v1
  condition: nemoretriever-graphic-elements-v1.deployed
  name: nvidia-nim-nemoretriever-graphic-elements-v1
  repository: alias:nvidia-nim
  version: 1.2.0
- alias: nemoretriever-table-structure-v1
  condition: nemoretriever-table-structure-v1.deployed
  name: nvidia-nim-nemoretriever-table-structure-v1
  repository: alias:nvidia-nim
  version: 1.2.0
- alias: nim-vlm-text-extraction
  condition: nim-vlm-text-extraction.deployed
  name: nim-vlm
  repository: alias:nemo-microservices
  version: 1.2.0-ea-v2
- alias: paddleocr-nim
  condition: paddleocr-nim.deployed
  name: nvidia-nim-paddleocr
  repository: alias:baidu-nim
  version: 1.2.0
- alias: text-embedding-nim
  condition: text-embedding-nim.deployed
  name: nvidia-nim-nv-embedqa-e5-v5
  repository: alias:nvidia-nim
  version: 1.5.0
- condition: nvidia-nim-llama-32-nv-embedqa-1b-v2.deployed
  name: nvidia-nim-llama-32-nv-embedqa-1b-v2
  repository: alias:nvidia-nim
  version: 1.5.0
- condition: riva-nim.deployed
  name: riva-nim
  repository: alias:nvidia-nim
  version: 1.0.0
- condition: milvusDeployed
  name: milvus
  repository: https://zilliztech.github.io/milvus-helm
  version: 4.1.11
- condition: redisDeployed
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - redis
  version: 19.1.3
- condition: zipkinDeployed
  name: zipkin
  repository: https://zipkin.io/zipkin-helm
  version: 0.1.2
- condition: otelDeployed
  name: opentelemetry-collector
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.78.1
description: NV-Ingest Microservice
maintainers:
- name: NVIDIA Corporation
  url: https://www.nvidia.com/
name: nv-ingest
type: application
version: 25.4.2
