apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "aiq.fullname" . }}
spec:
  gateways:
    - {{ .Values.ezua.virtualService.istioGateway }}
  hosts:
    - {{ .Values.ezua.virtualService.endpoint | required "\nValid .Values.ezua.virtualService.endpoint is required !" }}
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: aiq-frontend.{{.Release.Namespace}}.svc.cluster.local
        port:
          number: {{ .Values.aiq.apps.frontend.service.port }}