apiVersion: batch/v1
kind: Job
metadata:
  name: load-files-nv-ingest
  namespace: aira
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ngc-secret
      containers:
      - name: load-files-nv-ingest
        image: nvcr.io/nvidia/blueprint/aira-load-files:v1.1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: MILVUS_HOST
          value: "milvus.nv-nvidia-blueprint-rag.svc.cluster.local"
        - name: MILVUS_PORT
          value: "19530"
        - name: RAG_INGEST_URL
          value: "http://ingestor-server.nv-nvidia-blueprint-rag.svc.cluster.local:8082"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: MAX_UPLOAD_WAIT_TIME
          value: "5000"
        volumeMounts:
        - name: tempdata
          mountPath: /tmp-data
        - mountPath: /app/sync_files2.py
          name: sync-files2-volume
          subPath: sync_files2.py
      volumes:
      - name: tempdata
        emptyDir: {}
      - configMap:
          defaultMode: 420
          items:
          - key: sync_files2.py
            path: sync_files2.py
          name: sync-files2-cm
        name: sync-files2-volume

      restartPolicy: OnFailure 