{{/*
Copyright (c) 2024-2025, NVIDIA CORPORATION.  All rights reserved.

NVIDIA CORPORATION and its licensors retain all intellectual property
and proprietary rights in and to this software, related documentation
and any modifications thereto.  Any use, reproduction, disclosure or
distribution of this software and related documentation without an express
license agreement from NVIDIA CORPORATION is strictly prohibited.
*/}}

{{- if .Values.ngcSecret.create }}
{{- if .Values.ngcSecret.apiKey }}
---
# Docker registry secret for pulling images from nvcr.io
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.ngcImagePullSecretName }}
  labels:
    {{- include "rtdt.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "nvcr.io": {
          "username": "$oauthtoken",
          "password": {{ .Values.ngcSecret.apiKey | quote }},
          "auth": {{ printf "$oauthtoken:%s" .Values.ngcSecret.apiKey | b64enc | quote }}
        }
      }
    }
---
# NGC API key secret for NIM container authentication
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rtdt.ngcApiSecretName" . }}
  labels:
    {{- include "rtdt.labels" . | nindent 4 }}
type: Opaque
stringData:
  NGC_API_KEY: {{ .Values.ngcSecret.apiKey | quote }}
{{- end }}
{{- end }}
