apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "morpheus-vuln-analysis.fullname" . }}-env
  #namespace: {{ .Values.namespace }}
data:
  # Terminal type for containers. OPTIONAL: Only set if a specific terminal type is needed
  TERM: {{ .Values.env.TERM | quote }}
  # HuggingFace cache directory for caching models, datasets, and spaces locally 
  # OPTIONAL: Only used if fetching models/datasets from Hugging Face
  HF_HUB_CACHE: {{ .Values.env.HF_HUB_CACHE | quote }}
  # XDG cache home directory for caching temp files in linux. OPTIONAL: Defaults to $HOME/.cache
  XDG_CACHE_HOME: {{ .Values.env.XDG_CACHE_HOME | quote }}

  # Base URLs for various vulnerability and threat intelligence APIs
  # All can be OPTIONAL, but will limit access to security data

  # Common Weakness Enumeration API base URL
  CWE_DETAILS_BASE_URL: {{ .Values.env.CWE_DETAILS_BASE_URL | quote }}
  # Deps.dev API base URL
  DEPSDEV_BASE_URL: {{ .Values.env.DEPSDEV_BASE_URL | quote }}
  # FIRST.org API base URL
  FIRST_BASE_URL: {{ .Values.env.FIRST_BASE_URL | quote }}
  # GitHub Security Advisory API base URL
  GHSA_BASE_URL: {{ .Values.env.GHSA_BASE_URL | quote }}
  # National Vulnerability Database API base URL 
  NVD_BASE_URL: {{ .Values.env.NVD_BASE_URL | quote }}
  # Red Hat Security Advisory API base URL
  RHSA_BASE_URL: {{ .Values.env.RHSA_BASE_URL | quote }}
  # SerpAPI base URL 
  SERPAPI_BASE_URL: {{ .Values.env.SERPAPI_BASE_URL | quote }}
  # Ubuntu Security Notices API base URL
  UBUNTU_BASE_URL: {{ .Values.env.UBUNTU_BASE_URL | quote }}

  #URLs for accessing AI services. Require either NVIDIA_API_BASE or OPENAI_API_BASE & OPENAI_BASE_URL.

  # NVIDIA NGC API (OPTIONAL: Only needed for using NVIDIA hosted NIMs)
  NGC_API_BASE: {{ .Values.env.NGC_API_BASE | quote }}
  # NIM Embedder API base URL (MANDATORY)
  NIM_EMBED_BASE_URL: {{ .Values.env.NIM_EMBED_BASE_URL | quote }}
  # NVIDIA API base URL (OPTIONAL: needed if using NVIDIA NIMs)
  NVIDIA_API_BASE: {{ .Values.env.NVIDIA_API_BASE | quote }}
  # OpenAI API base URL (OPTIONAL: needed if using OpenAI LLMs)
  OPENAI_API_BASE: {{ .Values.env.OPENAI_API_BASE | quote }}
  # OpenAI base URL (OPTIONAL: needed if using OpenAI LLMs)
  OPENAI_BASE_URL: {{ .Values.env.OPENAI_BASE_URL | quote }}

  # Model names for LLM/embedding tasks. All are MANDATORY if overriding the default value of '-meta/llama-3.1-70b-instruct'

  # Checklist generation LLM model name 
  CHECKLIST_MODEL_NAME: {{ .Values.env.CHECKLIST_MODEL_NAME | quote }}
  # Code VDB retriever queries vector DB built from source code 
  CODE_VDB_RETRIEVER_MODEL_NAME: {{ .Values.env.CODE_VDB_RETRIEVER_MODEL_NAME | quote }}
  # Doc VDB retriever queries vector DB built from docs 
  DOC_VDB_RETRIEVER_MODEL_NAME: {{ .Values.env.DOC_VDB_RETRIEVER_MODEL_NAME | quote }}
  # CVE agent executor model name. Executes task list provided by checklist generation node.
  CVE_AGENT_EXECUTOR_MODEL_NAME: {{ .Values.env.CVE_AGENT_EXECUTOR_MODEL_NAME | quote }}
  # Summarization model name. Summarizes results of agent executor.
  SUMMARIZE_MODEL_NAME: {{ .Values.env.SUMMARIZE_MODEL_NAME | quote }}
  # Justification model name. Provides final CVE justification and rating. 
  JUSTIFY_MODEL_NAME: {{ .Values.env.JUSTIFY_MODEL_NAME | quote }}
  # Embedding model name. Creates embeddings from source code and docs.
  EMBEDDER_MODEL_NAME: {{ .Values.env.EMBEDDER_MODEL_NAME | quote }}

  #Settings for the task agent
  RETURN_INTERMEDIATE_STEPS: "{{ .Values.env.RETURN_INTERMEDIATE_STEPS | default false }}"
  MAX_ITERATIONS: "{{ .Values.env.MAX_ITERATIONS | default 10 }}"
  MAX_CONCURRENCY: "{{ .Values.env.MAX_CONCURRENCY | default 5 }}"