apiVersion: v1
appVersion: v2.0.0
description: An end to end Helm chart for the NVIDIA RAG Blueprint
name: nvidia-rag
type: application
version: v2.0.2

dependencies:
  - name: ingestor-server
    repository: "file://charts/ingestor-server"
    version: v2.0.0
    condition: ingestor-server.enabled
  - name: frontend
    repository: "file://charts/frontend"
    version: v1.0.0
    condition: frontend.enabled
